FROM httpd:alpine

WORKDIR /var/www/html

COPY conf/httpd.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 8080

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD test -f /var/www/html/index.html && nc 127.0.0.1 8080 || exit 1

