FROM nginx:alpine

WORKDIR /var/www/html
#/usr/share/nginx/html/

COPY conf/nginx.default.conf /etc/nginx/conf.d/default.conf

EXPOSE 8081

HEALTHCHECK --interval=30s --timeout=30s --start-period=5s --retries=3 \
    CMD test -f /var/www/html/index.html && nc 127.0.0.1 8081 || exit 1
